language: java

sudo: required

jdk: oraclejdk8

before_deploy:
    - "mvn -DskipTests package"
    - export PACK=$(ls target/yals.jar)

deploy:
   provider: releases
   api_key:
      secure: aad9c2b4c932a1205a4b71382d944c30b225e3ee
   file_glob: true
   file: "${PACK}"
   skip_cleanup: true
   on:
     repo: yadevee/yals
     all_branches: true
     tags: true

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
       - asm@virtalab.net
