sudo: required

services:
    - docker

language: java
jdk: oraclejdk8

env:
   global:
       - PROJECT=yals
       - G_TAG=${TRAVIS_TAG}
       - G_BRANCH=${TRAVIS_BRANCH}
       - T_BUILD=${TRAVIS_JOB_NUMBER}

after_success:
    - export D_REPO=${D_USER}/${PROJECT}
    - export G_TAG=`if [ "x$G_TAG" == "x" ]; then echo "-"; fi`
    - echo "Verbose info. Build $T_BUILD. Git branch $G_BRANCH. Git Tag $G_TAG"
    - export IS_TAG_BUILD=`if [ "$G_TAG" != "-" ]; then echo "yes"; else echo "no"; fi`

    - if [ "$IS_TAG_BUILD" == "yes" ]; then echo "Building tagged build for tag $G_TAG" &&  docker build -t $D_REPO:$G_TAG .; fi

    - if [ "$IS_TAG_BUILD" != "yes" ]; export D_POINTER_TAG=`if [ "$G_BRANCH" == "master" ]; then echo "stable"; elif [ "$G_BRANCH" == "trunk" ]; then echo "latest"; else echo "$G_BRANCH-latest"; fi`; fi
    - if [ "$IS_TAG_BUILD" != "yes" ]; echo "Building docker $D_REPO:travis-$T_BUILD"; fi
    - if [ "$IS_TAG_BUILD" != "yes" ]; docker build -t $D_REPO:travis-$T_BUILD .; fi
    - if [ "$IS_TAG_BUILD" != "yes" ]; echo "Adding additional pointer tag $D_REPO:$D_POINTER_TAG to travis-$T_BUILD"; fi
    - if [ "$IS_TAG_BUILD" == "yes" ]; docker tag $D_REPO:travis-$T_BUILD $D_REPO:$D_POINTER_TAG; fi

    - echo "Logging in to Docker hub as $D_USER"
    - docker login -u $D_USER -p $D_PASS
    - echo "Pushing image to $D_REPO"
    - docker push $D_REPO

notifications:
    email:
       - asm@virtalab.net

